### ISSUE TITLE
Getting an exception when trying to send Hello

### ISSUE THREAD

**Issue by quack3d** [GhostBassist/GooglePyNotify#8]
I'm getting the following when trying to make it say Hello.

`Getting chromecasts...
Wed Aug 15 08:35:04 2018 Server Starts - 0.0.0.0:90
10.0.0.10 - - [15/Aug/2018 08:36:00] "GET /Notify?Hello HTTP/1.1" 200 -
<html><head><meta http-equiv='refresh' content='0;url=.' /></head><body><h1>Notification Sent! <br>Hello</h1></body></html>
Generating MP3...
Sending notification...
10.0.0.10
----------------------------------------
Exception happened during processing of request from ('10.0.0.10', 8615)
Traceback (most recent call last):
  File "C:\Python36\lib\socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Python36\lib\socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "C:\Python36\lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python36\lib\socketserver.py", line 696, in __init__
    self.handle()
  File "C:\Python36\lib\http\server.py", line 418, in handle
    self.handle_one_request()
  File "C:\Python36\lib\http\server.py", line 406, in handle_one_request
    method()
  File ".\GooglePyNotify.py", line 34, in do_GET
    self.notify(str(notification))
  File ".\GooglePyNotify.py", line 75, in notify
    self.Cast(ip_add, mp3)
  File ".\GooglePyNotify.py", line 82, in Cast
    castdevice = next(cc for cc in CHROMECASTS if cc.device.model_name == "Google Home")
StopIteration
----------------------------------------
10.0.0.10 - - [15/Aug/2018 08:36:01] "GET / HTTP/1.1" 200 -`

**Comment by Gilumaro** [comment]
getting the exact same error message. Any solution for this?

**Comment by Camposmansi** [comment]
The same mistake

**Comment by Gilumaro** [comment]
Solution for me was to change "Google Home" to "Google Home Mini" 
so in GooglePyNotify.py change line 82 to the device name you have (for me a google home mini)
castdevice = next(cc for cc in CHROMECASTS if cc.device.model_name == "G                                     oogle Home Mini")

**Comment by Camposmansi** [comment]
Wow thank you. I also had problems with the port, I added it.
         url = "http: //" + ip_add + ": 8888/" + mp3
         print (url)

Now it's just missing that the language in es-ES does not work
